// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03AoYlEosstvba5yTevV7wenJcghXJZY',
    appId: '1:853994132327:web:260216d6ededef4d8455c2',
    messagingSenderId: '853994132327',
    projectId: 'esp-32-d9503',
    authDomain: 'esp-32-d9503.firebaseapp.com',
    databaseURL: 'https://esp-32-d9503-default-rtdb.firebaseio.com',
    storageBucket: 'esp-32-d9503.appspot.com',
    measurementId: 'G-7MVSQZSG23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0a2exYgAMz8pwpkIksm5oC4eZ0DJFbVI',
    appId: '1:853994132327:android:d223a82e588fa2e28455c2',
    messagingSenderId: '853994132327',
    projectId: 'esp-32-d9503',
    databaseURL: 'https://esp-32-d9503-default-rtdb.firebaseio.com',
    storageBucket: 'esp-32-d9503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyhz6n_nkHtuKYI_nMGRpLD8MbFfbHF4',
    appId: '1:853994132327:ios:5d5ff2171b6fbda98455c2',
    messagingSenderId: '853994132327',
    projectId: 'esp-32-d9503',
    databaseURL: 'https://esp-32-d9503-default-rtdb.firebaseio.com',
    storageBucket: 'esp-32-d9503.appspot.com',
    iosBundleId: 'com.example.aiHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyhz6n_nkHtuKYI_nMGRpLD8MbFfbHF4',
    appId: '1:853994132327:ios:0d9c9f1b2f03d6e48455c2',
    messagingSenderId: '853994132327',
    projectId: 'esp-32-d9503',
    databaseURL: 'https://esp-32-d9503-default-rtdb.firebaseio.com',
    storageBucket: 'esp-32-d9503.appspot.com',
    iosBundleId: 'com.example.aiHome.RunnerTests',
  );
}
